### ISSUE TITLE
authentication error

### ISSUE THREAD

**Issue by CaduOlegario** [2BAD/bitrix#16]
Good morning, I'm having trouble using and configuring oauth authentication and from what I realized it is no longer possible to use via webhook, I would like to put a tutorial on how to use oauth from bitrix24 or release via webhook. thanks. Obs. Was translated in google translator in case of spelling errors

**Comment by mrhyde** [comment]
Hi @CaduOlegario, sorry for such a late reply!
Unfortunately there is no easy way to get access token programmatically since it will require user input (login and password) at least if you are following official documentation.
We do recommend using incoming webhook URL in client constructor and omit access tokens ([docs](https://github.com/2BAD/bitrix#authentication))
